# .bashrc

# User specific aliases and functions

# Terminal setting
export PS1='\[\033[31m\][\u@\h \W]\[\033[00m\]$ '
export GREP_OPTIONS='--color=auto' GREP_COLOR='1;32'
export LS_OPTIONS='-l --color=always' LS_COLORS='rs=0:di=01;34:ln=01;36:mh=00:pi=40;33'

# Aliases
alias ls='ls $LS_OPTIONS'
alias vmssh='ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ServerAliveInterval=100'
alias vmscp='scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
alias venew='virtualenv-3 ./.venv-$(basename $(pwd))'
alias veact='source ./.venv-$(basename $(pwd))/bin/activate'

# Load various bash completions
declare -a comp_scripts=(
	"/etc/bash_completion.d/git"
	"/usr/share/git-core/contrib/completion/git-prompt.sh"
	"/etc/bash_completion.d/git-completion.bash"
	"/etc/profile.d/bash_completion.sh"
	"~/.git-completion.bash"
	)
for script in "${comp_scripts[@]}"; do
  if [ -f $script ]; then
    . $script
  fi
done

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
