#git clone https://github.com/redhat-openstack/infrared.git
#cd infrared/
#venv-create
#venv-activate
#pip install -U pip
#pip install -U setuptools
#pip install .

#cp infrared.cfg.example infrared.cfg
#cat > ansible.cfg << EOF
#[defaults]
#host_key_checking = False
#forks = 500
#pipelining = True
#timeout = 30
#force_color = 1
#roles_path = infrared/common/roles
#library = infrared/common/library
#filter_plugins = infrared/common/filter_plugins
#callback_plugins = infrared/common/callback_plugins
#callback_whitelist = timer,profile_tasks,junit_report

#[ssh_connection]
#control_path = $(pwd)/.venv-infrared/%%h-%%r
#EOF
